uploads = []
outputs = []

[[generated]]
id = "Q_fFRIpZrgzX0GJASwGR5"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "BoKc3aCyP4EiLGIPPZRky"
uri = "file://artifacts/mobile/assets/images/resident-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "xf9l1m_rCk4nJTLrv2mES"
uri = "file://artifacts/mobile/assets/images/resident-2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "rJzityYBAdTTheJ-n0XXt"
uri = "file://artifacts/mobile/assets/images/resident-3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "5a2tF3DbIFRpx4pUIKVh3"
uri = "file://artifacts/mobile/assets/images/resident-4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "P_xy2MF1cCJKiId9mWd9k"
uri = "file://artifacts/mobile/assets/images/resident-5.png"
type = "image"
title = "generated_image"

[[generated]]
id = "VYhaNXOHsfqYQE8Rh4E_C"
uri = "file://artifacts/mobile/assets/images/resident-6.png"
type = "image"
title = "generated_image"

[[generated]]
id = "S5vE_80A4iHpwT31FP_JQ"
uri = "file://artifacts/mobile/assets/images/resident-7.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Is_16ELj6YP_NHCBZBypt"
uri = "file://artifacts/mobile/assets/images/resident-8.png"
type = "image"
title = "generated_image"

[[generated]]
id = "CcVhOSgREusJBQAEooRr4"
uri = "file://artifacts/mobile/assets/images/resident-9.png"
type = "image"
title = "generated_image"

[[generated]]
id = "2aeV4-s_x6vrwPzjBHMS2"
uri = "file://artifacts/mobile/assets/images/resident-10.png"
type = "image"
title = "generated_image"

[[generated]]
id = "rO1QncV1lVLNe2v_PXwVN"
uri = "file://artifacts/mobile/assets/images/resident-11.png"
type = "image"
title = "generated_image"

[[generated]]
id = "2AwHdhBQ4yX-krf6XEFjB"
uri = "file://artifacts/mobile/assets/images/resident-12.png"
type = "image"
title = "generated_image"

[[generated]]
id = "QKoWOvmPZOBU_fczsaqQ_"
uri = "file://artifacts/mobile/assets/images/resident-13.png"
type = "image"
title = "generated_image"

[[generated]]
id = "GWeSTtjkdHxOoDRSfZphc"
uri = "file://artifacts/mobile/assets/images/resident-14.png"
type = "image"
title = "generated_image"

[[generated]]
id = "lLWGEeEqIhpZApgF2qH25"
uri = "file://artifacts/mobile/assets/images/resident-15.png"
type = "image"
title = "generated_image"

[[generated]]
id = "18FIGMnBHO9E2p1tArsBs"
uri = "file://artifacts/mobile/assets/images/resident-16.png"
type = "image"
title = "generated_image"

[[generated]]
id = "SLB2Rgjmh0Mt9sJZjO8qG"
uri = "file://artifacts/mobile/assets/images/resident-17.png"
type = "image"
title = "generated_image"

[[generated]]
id = "u46lUwQfWM9kLs3sWdk6z"
uri = "file://artifacts/mobile/assets/images/resident-18.png"
type = "image"
title = "generated_image"

[[generated]]
id = "9T8oM0S5PpZvsGQi3T82H"
uri = "file://artifacts/mobile/assets/images/resident-19.png"
type = "image"
title = "generated_image"

[[generated]]
id = "JKr2foB7Wc0u-tsQMawAb"
uri = "file://artifacts/mobile/assets/images/resident-20.png"
type = "image"
title = "generated_image"

[[generated]]
id = "MPMP0Cx8sTvbJicdjQqC-"
uri = "file://artifacts/mobile/assets/images/resident-21.png"
type = "image"
title = "generated_image"

[[generated]]
id = "P8M83eONgsZDBJbl2UmJL"
uri = "file://artifacts/mobile/assets/images/resident-22.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ufqAHFcJjjYx8OGUgC7_L"
uri = "file://artifacts/mobile/assets/images/resident-23.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gk_ssil_GlwJHiufqNJNC"
uri = "file://artifacts/mobile/assets/images/resident-24.png"
type = "image"
title = "generated_image"

[[generated]]
id = "WpcSqQhJUDrTsMMW6xjjM"
uri = "file://artifacts/mobile/assets/images/resident-25.png"
type = "image"
title = "generated_image"

[[generated]]
id = "dnforbG9OywpYrOCmkLh2"
uri = "file://artifacts/mobile/assets/images/resident-26.png"
type = "image"
title = "generated_image"

[[generated]]
id = "MISBrzBf6rgduqGuPbQZP"
uri = "file://artifacts/mobile/assets/images/resident-27.png"
type = "image"
title = "generated_image"

[[generated]]
id = "JwzsKc5OJF8GhwRMcZM0U"
uri = "file://artifacts/mobile/assets/images/resident-28.png"
type = "image"
title = "generated_image"

[[generated]]
id = "8WN5r6LOl3Mu9hKx-WRaX"
uri = "file://artifacts/mobile/assets/images/resident-29.png"
type = "image"
title = "generated_image"

[[generated]]
id = "oTGY9h332fj8pWCX_MIYA"
uri = "file://artifacts/mobile/assets/images/resident-30.png"
type = "image"
title = "generated_image"
